# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "composer"
    directory: "/vendor-bin/php-cs-fixer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

  - package-ecosystem: "composer"
    directory: "/vendor-bin/phpstan"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "composer"
    directory: "/vendor-bin/psalm"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
